#!/usr/bin/env python
#################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#################################################################################

import rospy
import os
import pickle
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist
import numpy as np

class follower:
    def __init__(self):
        rospy.loginfo('Follower node initialized')
        self.config_dir = os.path.join(os.path.dirname(__file__))
####os.path.dirname()返回文件路径; os.path.join()文件路径拼接，以从后往前的第一个“/”路径开始拼接，之前的路径省略。####
        self.config_dir = self.config_dir.replace('nodes', 'config')
####replace()替换函数，replace（old，new，max）new替换old，次数不超过max次
        self.pub = rospy.Publisher('cmd_vel', Twist, queue_size = 1)
        self.clf = pickle.load(open(self.config_dir + '/clf', "rb"))
####pickle.load()序列化函数,pickle.load(file)函数的功能：将file中的对象序列化读出。
        self.clf2 = pickle.load(open(self.config_dir + '/clf2', "rb"))
        self.labels = {'30_0':0, '30_l':1, '30_r':2, '45_0':3, '45_l':4, '45_r':5,'15_0':6, 'empty':7}
        rospy.loginfo('Tree initialized')
        self.follow()

    def check_people(self):
        laser_data=[]
        laser_data_set=[]
        result=[]
        ret = 0
        self.msg = rospy.wait_for_message("scan_filtered", LaserScan)

        for i in range(70,-2,-1) + range(359, 289,-1):
####对雷达扫描角度进行剪切####

            if   np.nan_to_num( self.msg.intensities[i] ) != 0 :
####numpy.nan_to_num函数，将nan元素转换成num数值####
                 laser_data.append(np.nan_to_num(self.msg.intensities[i]))

            elif (i+1) in range(70,-2,-1) + range(359, 289,-1) and (i-1) in range(70,-2,-1) + range(359, 289,-1) and np.nan_to_num(self.msg.intensities[i]) == 0:
                 laser_data.append((np.nan_to_num(self.msg.intensities[i+1])+np.nan_to_num(self.msg.intensities[i-1]))/2)

            else :
                 laser_data.append(np.nan_to_num(self.msg.intensities[i]))

        laser_data_set.append(laser_data)

        [x for (x , y) in self.labels.iteritems() if y == self.clf2.predict(laser_data_set) ] ## Predict the position
####iteritems()返回迭代器，一次返回一个键值对

        if result == ['empty']:
            ret = 0

        else:
            ret = 1

        return ret

    def laser_scan(self):
        data_test=[]
        data_test_set=[]
        self.msg = rospy.wait_for_message("scan_filtered", LaserScan)

        for i in range(70,-2,-1) + range(359, 289,-1):

            if   np.nan_to_num( self.msg.ranges[i] ) != 0 :
                 data_test.append(np.nan_to_num(self.msg.ranges[i]))

            elif (i+1) in range(70,-2,-1) + range(359, 289,-1) and (i-1) in range(70,-2,-1) + range(359, 289,-1) and np.nan_to_num(self.msg.ranges[i]) == 0:
                 data_test.append((np.nan_to_num(self.msg.ranges[i+1])+np.nan_to_num(self.msg.ranges[i-1]))/2)

            else :
                 data_test.append(np.nan_to_num(self.msg.ranges[i]))

        data_test_set.append(data_test)

        return [x for (x , y) in self.labels.iteritems() if y == self.clf.predict(data_test_set) ] 
###根据雷达扫描数据，估计扫描范围内物体的位置###

    def follow(self):
        while not rospy.is_shutdown():
            check = self.check_people()
            if  check == 1:
                x = self.laser_scan()
                twist = Twist()
                ###针对每个位置进行速度指令###
                if  x == ['30_0']:
                    twist.linear.x  = 0.13;      	twist.angular.z = 0.0;
                elif x== ['30_l']:
                    twist.linear.x  = 0.10; 		twist.angular.z = 0.4;
                elif x== ['30_r']:
                    twist.linear.x  = 0.10; 		twist.angular.z = -0.4;
                elif x== ['45_0']:
                    twist.linear.x  = 0.13;      	twist.angular.z = 0.0;
                elif x== ['45_l']:
                    twist.linear.x  = 0.10; 		twist.angular.z = 0.3;
                elif x== ['45_r']:
                    twist.linear.x  = 0.10; 		twist.angular.z = -0.3;
                elif x== ['15_0']:
                    twist.linear.x  = 0.0;	      	twist.angular.z = 0.0;
                elif x== ['empty']:
                    twist.linear.x  = 0.0;	 	    twist.angular.z = 0.0;
                else:
                    twist.linear.x  = 0.0;		    twist.angular.z = 0.0;

                self.pub.publish(twist)

            elif check == 0:
                x = self.laser_scan()
                twist = Twist()

                if x== ['empty']:
                    twist.linear.x  = 0.0;		twist.angular.z = 0.0;

                else:
                    twist.linear.x  = 0.0; 		twist.angular.z = 0.4;

                self.pub.publish(twist)

def main():

    rospy.init_node('follower', anonymous=True)

    try:
        follow = follower()
    except rospy.ROSInterruptException:
        pass    #print("Shutting down")

if __name__ == '__main__':
    main()
